const Mats={
    huTao:{
        text:'胡桃木',
        matType:'MeshLambertMaterial',
        mapParam:{
            imgSrc:'/src/images/huTao.jpg',
            size:.3,
        }
    },
    pingGuo:{
        text:'苹果木',
        matType:'MeshLambertMaterial',
        mapParam:{
            imgSrc:'/src/images/pingGuo.jpg',
            size:.3,
        }
    },
    ciZhuan1:{
        text:'瓷砖1',
        matType:'MeshPhongMaterial',
        mapParam:{
            imgSrc:'/src/images/ciZhuan1.jpg',
            size:[.2,.1],
        }
    },
    lvMoSha:{
        text:'铝磨砂',
        matType:'MeshPhongMaterial',
        color:0xcccccc,
    },
}
export default Mats;